sources:
- id: echo-api
  type: http
  config:
    base_url: https://api.dnb.nl/echo-api
    headers:
      Ocp-Apim-Subscription-Key: ${DNB_SUBSCRIPTION_KEY}
    timeout: 30
tools:
- id: retrieve-resource
  source_id: echo-api
  method: GET
  path: /helloworld
  description: Retrieve 'Hello World'
