sources:
  echo-api:
    kind: http
    baseUrl: https://api.dnb.nl/echo-api
    headers:
      Ocp-Apim-Subscription-Key: ${DNB_SUBSCRIPTION_KEY_DEV}
    timeout: 30s
tools:
  retrieve-resource:
    kind: http
    source: echo-api
    method: GET
    path: /helloworld
    description: Retrieve 'Hello World'
toolsets:
  dnb-echo-tools:
  - retrieve-resource
