sources:
  public_register_api:
    kind: http
    baseUrl: https://api.dnb.nl/publicdata/v1
    headers:
      Ocp-Apim-Subscription-Key: ${DNB_SUBSCRIPTION_KEY_DEV}
    timeout: 30s
tools:
  get_api_publicregister_registercode_organizations:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.registerCode}}/Organizations
    description: Retrieve latest relation numbers for register.
    queryParams:
    - name: page
      type: integer
      description: The page number. Where 1 indicates the first page. Defaults to
        the first page.
      required: false
    - name: pageSize
      type: integer
      description: The amount of records one page contains. Defaults to 10 records.
        Maximum of 25 records is allowed.
      required: false
    pathParams:
    - name: registerCode
      type: string
      description: The register code.
      required: true
  get_api_publicregister_registercode_organizations_historicalreco:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.registerCode}}/Organizations/historicalrecord/{{.date}}
    description: Retrieve historical relation numbers for register.
    queryParams:
    - name: page
      type: integer
      description: The page number. Where 1 indicates the first page. Defaults to
        the first page.
      required: false
    - name: pageSize
      type: integer
      description: The amount of records one page contains. Defaults to 10 records.
        Maximum of 25 records is allowed.
      required: false
    pathParams:
    - name: registerCode
      type: string
      description: The register code.
      required: true
    - name: date
      type: string
      description: The date of when the publication was published.
      required: true
  get_api_publicregister_languagecode_registercode_organizations:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.languageCode}}/{{.registerCode}}/Organizations
    description: Retrieve latest organizations for relation numbers.
    queryParams:
    - name: relationNumbers
      type: string
      description: The relation numbers. Duplicates and empty values are ignored.
        Maximum of 25 relation numbers can be provided.
      required: false
    pathParams:
    - name: languageCode
      type: string
      description: The language code.
      required: true
    - name: registerCode
      type: string
      description: The register code.
      required: true
  get_api_publicregister_languagecode_registercode_organizations_h:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.languageCode}}/{{.registerCode}}/Organizations/historicalrecord/{{.date}}
    description: Retrieve historical organizations for relation numbers.
    queryParams:
    - name: relationNumbers
      type: string
      description: The relation numbers. Duplicates and empty values are ignored.
        Maximum of 25 relation numbers can be provided.
      required: false
    pathParams:
    - name: languageCode
      type: string
      description: The language code.
      required: true
    - name: registerCode
      type: string
      description: The register code.
      required: true
    - name: date
      type: string
      description: The date of when the publication was published.
      required: true
  get_api_publicregister_languagecode_publications_registercode:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.languageCode}}/Publications/{{.registerCode}}
    description: Retrieve latest publication.
    queryParams:
    - name: page
      type: integer
      description: The page number. Where 1 indicates the first page. Defaults to
        the first page.
      required: false
    - name: pageSize
      type: integer
      description: The amount of records one page contains. Defaults to 10 records.
        Maximum of 25 records is allowed.
      required: false
    pathParams:
    - name: languageCode
      type: string
      description: The publication in the specified language.
      required: true
    - name: registerCode
      type: string
      description: The publication in the specified register.
      required: true
  get_api_publicregister_languagecode_publications_registercode_hi:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.languageCode}}/Publications/{{.registerCode}}/historicalrecord/{{.date}}
    description: Retrieve historical publication.
    queryParams:
    - name: page
      type: integer
      description: The page number. Where 1 indicates the first page. Defaults to
        the first page.
      required: false
    - name: pageSize
      type: integer
      description: The amount of records one page contains. Defaults to 10 records.
        Maximum of 25 records is allowed.
      required: false
    pathParams:
    - name: languageCode
      type: string
      description: The publication in the specified language.
      required: true
    - name: registerCode
      type: string
      description: The publication in the specified register.
      required: true
    - name: date
      type: string
      description: The date of when the publication was published.
      required: true
  get_api_publicregister_languagecode_publications_search_register:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.languageCode}}/Publications/search
    description: Search publications.
    queryParams:
    - name: RegisterCode
      type: string
      description: (Required) Search within a specific register.
      required: true
    - name: OrganizationName
      type: string
      description: (Optional) The name of the organization. Used as a wild cart search
        on the trade, statutory, and official names.
      required: false
    - name: ActArticleName
      type: string
      description: (Optional) Search registrations based on the act article name.
      required: false
    - name: page
      type: integer
      description: The page number. Where 1 indicates the first page. Defaults to
        the first page.
      required: false
    - name: pageSize
      type: integer
      description: The amount of records one page contains. Defaults to 10 records.
        Maximum of 25 records is allowed.
      required: false
    pathParams:
    - name: languageCode
      type: string
      description: The publication in the specified language.
      required: true
  get_api_publicregister_languagecode_registercode_registerarticle:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.languageCode}}/{{.registerCode}}/RegisterArticles
    description: Retrieve latest act articles.
    pathParams:
    - name: languageCode
      type: string
      description: 'Parameter: languageCode'
      required: true
    - name: registerCode
      type: string
      description: 'Parameter: registerCode'
      required: true
  get_api_publicregister_registers:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/Registers
    description: Retrieve all registers.
  get_api_publicregister_languagecode_registercode_registrations_a:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/{{.languageCode}}/{{.registerCode}}/Registrations/ActArticleNames/historicalrecord/{{.date}}
    description: Retrieve historical act article names.
    pathParams:
    - name: languageCode
      type: string
      description: The language code.
      required: true
    - name: registerCode
      type: string
      description: The register code.
      required: true
    - name: date
      type: string
      description: The date of when the publication was published.
      required: true
  get_api_publicregister_supportedlanguages:
    kind: http
    source: public_register_api
    method: GET
    path: /api/publicregister/SupportedLanguages
    description: Retrieve languages.
toolsets:
  dnb_public_register_tools:
  - get_api_publicregister_registercode_organizations
  - get_api_publicregister_registercode_organizations_historicalreco
  - get_api_publicregister_languagecode_registercode_organizations
  - get_api_publicregister_languagecode_registercode_organizations_h
  - get_api_publicregister_languagecode_publications_registercode
  - get_api_publicregister_languagecode_publications_registercode_hi
  - get_api_publicregister_languagecode_publications_search_register
  - get_api_publicregister_languagecode_registercode_registerarticle
  - get_api_publicregister_registers
  - get_api_publicregister_languagecode_registercode_registrations_a
  - get_api_publicregister_languagecode_registercode_registrations_a
  - get_api_publicregister_supportedlanguages
