[tool.poetry]
name = "orkhon"
version = "0.1.0"
description = ""
authors = ["Px8Studio <info@px8.studio>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
toolbox-langchain = "^0.5.2"
langchain-google-vertexai = "^2.1.2"
langgraph = "^0.6.10"
google-adk = "^1.16.0"
uv = "^0.9.3"
toolbox-core = "^0.5.2"


[tool.poetry.group.dev.dependencies]
openapi-python-client = "^0.26.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
