sources:
  echo_api:
    kind: http
    baseUrl: https://api.dnb.nl/echo-api
    headers:
      Ocp-Apim-Subscription-Key: ${DNB_SUBSCRIPTION_KEY_PROD}
    timeout: 30s
tools:
  retrieve_resource:
    kind: http
    source: echo_api
    method: GET
    path: /helloworld
    description: Retrieve 'Hello World'
toolsets:
  dnb_echo_tools:
  - retrieve_resource
